### ISSUE TITLE
$db is undefined in get_dbi_handle

### ISSUE THREAD

**Issue by swelljoe** [virtualmin/virtualmin-oracle#1]
In this line:

``` perl
my $cstr = $config{'host'} ? "host=$config{'host'};sid=$db" : $db;
```

https://github.com/virtualmin/virtualmin-oracle/blob/master/virtualmin-oracle-lib.pl#L181

And on a subsequent line, $db is used, but undefined. I'm not sure where it ought to be coming from.

**Comment by jcameron** [comment]
It should be the arg to the get_dbi_handle function. I'll fix that..
